// <auto-generated />
using hackathon.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace hackathon.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523000000_AddPartialIndexesAndAuditTrigger")]
    partial class AddPartialIndexesAndAuditTrigger
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model is unchanged from InitialCreate; this migration only adds raw SQL objects
            // (partial indexes and PostgreSQL trigger) that are not tracked in the EF Core model.
        }
    }
}
