// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hackathon.API.Data;

#nullable disable

namespace hackathon.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522222001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hackathon.API.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("action");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("actor_role");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterState")
                        .HasColumnType("text")
                        .HasColumnName("after_state");

                    b.Property<string>("BeforeState")
                        .HasColumnType("text")
                        .HasColumnName("before_state");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("source");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("Action")
                        .HasDatabaseName("ix_audit_logs_action");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_logs_actor_user_id");

                    b.HasIndex("EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_id");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("ix_audit_logs_entity_type");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_logs_timestamp");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("hackathon.API.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("ChargerId")
                        .HasColumnType("uuid")
                        .HasColumnName("charger_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CsmsIdTag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("csms_id_tag");

                    b.Property<string>("CsmsSyncStatus")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("csms_sync_status");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("ReasonForOverride")
                        .HasColumnType("text")
                        .HasColumnName("reason_for_override");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VehicleMake")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_make");

                    b.Property<string>("VehicleModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_model");

                    b.HasKey("Id")
                        .HasName("pk_bookings");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_bookings_actor_user_id");

                    b.HasIndex("ChargerId")
                        .HasDatabaseName("ix_bookings_charger_id");

                    b.HasIndex("CsmsSyncStatus")
                        .HasDatabaseName("ix_bookings_csms_sync_status");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_bookings_start_time");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_bookings_state");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_bookings_user_id");

                    b.HasIndex("UserId", "State", "StartTime")
                        .HasDatabaseName("ix_bookings_user_state_day");

                    b.HasIndex("ChargerId", "State", "StartTime", "EndTime")
                        .HasDatabaseName("ix_bookings_charger_state_time");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("hackathon.API.Models.Charger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("ConnectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("connector_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalStationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_station_id");

                    b.Property<DateTime?>("LastCsmsSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_csms_sync_at");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_chargers");

                    b.HasIndex("ExternalStationId")
                        .IsUnique()
                        .HasDatabaseName("uq_chargers_external_station_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_chargers_location_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_chargers_status");

                    b.ToTable("chargers", (string)null);
                });

            modelBuilder.Entity("hackathon.API.Models.ChargingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("ChargerId")
                        .HasColumnType("uuid")
                        .HasColumnName("charger_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CsmsSessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("csms_session_id");

                    b.Property<decimal>("EnergyKwh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("energy_kwh");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<DateTime?>("StopTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stop_time");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VehicleMake")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_make");

                    b.Property<string>("VehicleModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_model");

                    b.HasKey("Id")
                        .HasName("pk_charging_sessions");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("uq_charging_sessions_booking_id");

                    b.HasIndex("ChargerId")
                        .HasDatabaseName("ix_charging_sessions_charger_id");

                    b.HasIndex("CsmsSessionId")
                        .HasDatabaseName("ix_charging_sessions_csms_session_id");

                    b.HasIndex("Source")
                        .HasDatabaseName("ix_charging_sessions_source");

                    b.HasIndex("StartTime")
                        .HasDatabaseName("ix_charging_sessions_start_time");

                    b.HasIndex("State")
                        .HasDatabaseName("ix_charging_sessions_state");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_charging_sessions_user_id");

                    b.ToTable("charging_sessions", (string)null);
                });

            modelBuilder.Entity("hackathon.API.Models.EligibleEvUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("BadgeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("badge_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EligibilityStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("eligibility_status");

                    b.Property<DateTime>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PrivacyAcknowledgementStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("privacy_acknowledgement_status");

                    b.Property<string>("SiteContext")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("site_context");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VehicleMake")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_make");

                    b.Property<string>("VehicleModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_model");

                    b.Property<string>("WorkplaceRegistryEid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("workplace_registry_eid");

                    b.HasKey("Id")
                        .HasName("pk_eligible_ev_users");

                    b.HasIndex("BadgeId")
                        .IsUnique()
                        .HasDatabaseName("uq_eligible_ev_users_badge_id");

                    b.HasIndex("EligibilityStatus")
                        .HasDatabaseName("ix_eligible_ev_users_eligibility_status");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_eligible_ev_users_user_id");

                    b.HasIndex("WorkplaceRegistryEid")
                        .IsUnique()
                        .HasDatabaseName("uq_eligible_ev_users_eid");

                    b.ToTable("eligible_ev_users", (string)null);
                });

            modelBuilder.Entity("hackathon.API.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_locations_code");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("hackathon.API.Models.MaintenanceBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("ChargerId")
                        .HasColumnType("uuid")
                        .HasColumnName("charger_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_blocks");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_maintenance_blocks_actor_user_id");

                    b.HasIndex("ChargerId")
                        .HasDatabaseName("ix_maintenance_blocks_charger_id");

                    b.HasIndex("ChargerId", "StartTime", "EndTime")
                        .HasDatabaseName("ix_maintenance_blocks_time_range");

                    b.ToTable("maintenance_blocks", (string)null);
                });

            modelBuilder.Entity("hackathon.API.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AudienceUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("audience_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("channel");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("delivery_status");

                    b.Property<Guid?>("LinkedBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_booking_id");

                    b.Property<Guid?>("LinkedChargerId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_charger_id");

                    b.Property<Guid?>("LinkedSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_session_id");

                    b.Property<JsonDocument>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<bool>("ReadState")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("read_state");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("severity");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("TriggerEvent")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("trigger_event");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("AudienceUserId")
                        .HasDatabaseName("ix_notifications_audience_user_id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_notifications_correlation_id");

                    b.HasIndex("LinkedBookingId")
                        .HasDatabaseName("ix_notifications_linked_booking_id");

                    b.HasIndex("LinkedChargerId")
                        .HasDatabaseName("ix_notifications_linked_charger_id");

                    b.HasIndex("LinkedSessionId")
                        .HasDatabaseName("ix_notifications_linked_session_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_notifications_timestamp");

                    b.HasIndex("TriggerEvent")
                        .HasDatabaseName("ix_notifications_trigger_event");

                    b.HasIndex("AudienceUserId", "ReadState")
                        .HasDatabaseName("ix_notifications_read_state");

                    b.HasIndex("Channel", "DeliveryStatus")
                        .HasDatabaseName("ix_notifications_channel_status");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("hackathon.API.Models.PrivacyAcknowledgement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PrivacyNoticeId")
                        .HasColumnType("uuid")
                        .HasColumnName("privacy_notice_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_privacy_acknowledgements");

                    b.HasIndex("PrivacyNoticeId")
                        .HasDatabaseName("ix_privacy_acknowledgements_privacy_notice_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_privacy_acks_user_id");

                    b.HasIndex("UserId", "PrivacyNoticeId")
                        .IsUnique()
                        .HasDatabaseName("uq_privacy_acks_user_notice");

                    b.ToTable("privacy_acknowledgements", (string)null);
                });

            modelBuilder.Entity("hackathon.API.Models.PrivacyNotice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<bool>("IsCurrentVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_current_version");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_privacy_notices");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("uq_privacy_notices_version");

                    b.ToTable("privacy_notices", (string)null);
                });

            modelBuilder.Entity("hackathon.API.Models.SystemConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_system_configs");

                    b.ToTable("system_configs", (string)null);
                });

            modelBuilder.Entity("hackathon.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_users_email");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("hackathon.API.Models.Booking", b =>
                {
                    b.HasOne("hackathon.API.Models.User", "ActorUser")
                        .WithMany("ActorBookings")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_bookings_users_actor_user_id");

                    b.HasOne("hackathon.API.Models.Charger", "Charger")
                        .WithMany("Bookings")
                        .HasForeignKey("ChargerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_chargers_charger_id");

                    b.HasOne("hackathon.API.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_user_id");

                    b.Navigation("ActorUser");

                    b.Navigation("Charger");

                    b.Navigation("User");
                });

            modelBuilder.Entity("hackathon.API.Models.Charger", b =>
                {
                    b.HasOne("hackathon.API.Models.Location", "Location")
                        .WithMany("Chargers")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_chargers_locations_location_id");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("hackathon.API.Models.ChargingSession", b =>
                {
                    b.HasOne("hackathon.API.Models.Booking", "Booking")
                        .WithOne("ChargingSession")
                        .HasForeignKey("hackathon.API.Models.ChargingSession", "BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_charging_sessions_bookings_booking_id");

                    b.HasOne("hackathon.API.Models.Charger", "Charger")
                        .WithMany("ChargingSessions")
                        .HasForeignKey("ChargerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_charging_sessions_chargers_charger_id");

                    b.HasOne("hackathon.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_charging_sessions_users_user_id");

                    b.Navigation("Booking");

                    b.Navigation("Charger");

                    b.Navigation("User");
                });

            modelBuilder.Entity("hackathon.API.Models.EligibleEvUser", b =>
                {
                    b.HasOne("hackathon.API.Models.User", "User")
                        .WithOne("EligibleEvUser")
                        .HasForeignKey("hackathon.API.Models.EligibleEvUser", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eligible_ev_users_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("hackathon.API.Models.MaintenanceBlock", b =>
                {
                    b.HasOne("hackathon.API.Models.User", "ActorUser")
                        .WithMany("MaintenanceBlocks")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_blocks_users_actor_user_id");

                    b.HasOne("hackathon.API.Models.Charger", "Charger")
                        .WithMany("MaintenanceBlocks")
                        .HasForeignKey("ChargerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_blocks_chargers_charger_id");

                    b.Navigation("ActorUser");

                    b.Navigation("Charger");
                });

            modelBuilder.Entity("hackathon.API.Models.Notification", b =>
                {
                    b.HasOne("hackathon.API.Models.User", "AudienceUser")
                        .WithMany("Notifications")
                        .HasForeignKey("AudienceUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_audience_user_id");

                    b.HasOne("hackathon.API.Models.Booking", "LinkedBooking")
                        .WithMany("Notifications")
                        .HasForeignKey("LinkedBookingId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_bookings_linked_booking_id");

                    b.HasOne("hackathon.API.Models.Charger", "LinkedCharger")
                        .WithMany("Notifications")
                        .HasForeignKey("LinkedChargerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_chargers_linked_charger_id");

                    b.HasOne("hackathon.API.Models.ChargingSession", "LinkedSession")
                        .WithMany("Notifications")
                        .HasForeignKey("LinkedSessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_charging_sessions_linked_session_id");

                    b.Navigation("AudienceUser");

                    b.Navigation("LinkedBooking");

                    b.Navigation("LinkedCharger");

                    b.Navigation("LinkedSession");
                });

            modelBuilder.Entity("hackathon.API.Models.PrivacyAcknowledgement", b =>
                {
                    b.HasOne("hackathon.API.Models.PrivacyNotice", "PrivacyNotice")
                        .WithMany("PrivacyAcknowledgements")
                        .HasForeignKey("PrivacyNoticeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_privacy_acknowledgements_privacy_notices_privacy_notice_id");

                    b.HasOne("hackathon.API.Models.User", "User")
                        .WithMany("PrivacyAcknowledgements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_privacy_acknowledgements_users_user_id");

                    b.Navigation("PrivacyNotice");

                    b.Navigation("User");
                });

            modelBuilder.Entity("hackathon.API.Models.Booking", b =>
                {
                    b.Navigation("ChargingSession");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("hackathon.API.Models.Charger", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ChargingSessions");

                    b.Navigation("MaintenanceBlocks");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("hackathon.API.Models.ChargingSession", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("hackathon.API.Models.Location", b =>
                {
                    b.Navigation("Chargers");
                });

            modelBuilder.Entity("hackathon.API.Models.PrivacyNotice", b =>
                {
                    b.Navigation("PrivacyAcknowledgements");
                });

            modelBuilder.Entity("hackathon.API.Models.User", b =>
                {
                    b.Navigation("ActorBookings");

                    b.Navigation("Bookings");

                    b.Navigation("EligibleEvUser");

                    b.Navigation("MaintenanceBlocks");

                    b.Navigation("Notifications");

                    b.Navigation("PrivacyAcknowledgements");
                });
#pragma warning restore 612, 618
        }
    }
}
